from sqlalchemy import Column, Integer, String, Numeric, Boolean, Text, DateTime
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class FundPlan(Base):
    __tablename__ = 'fund_plans'

    id = Column(Integer, primary_key=True)
    plan_id = Column(Integer)
    basic_name = Column(String(255))
    short_name = Column(String(255))
    plan_name = Column(String(255))
    basic_short_name = Column(String(255))
    scheme_name = Column(String(255))
    amc_id = Column(Integer)
    category_id = Column(Integer)
    type_id = Column(Integer)
    face_value = Column(Numeric)
    min_initial_investment = Column(Integer)
    min_subsequent_investment = Column(Integer)
    min_withdrawl_amount = Column(Integer)
    sip = Column(Boolean)
    min_subsequent_sip_investment = Column(Integer)
    sip_note = Column(Text)
    swp = Column(Boolean)
    min_swp_widw = Column(Integer)
    stp = Column(Boolean)
    min_balance = Column(Integer)
    redemption_note = Column(Text)
    equity_max = Column(Integer)
    equity_min = Column(Integer)
    debt_max = Column(Integer)
    debt_min = Column(Integer)
    money_mkt_max = Column(Integer)
    money_mkt_min = Column(Integer)
    issue_open = Column(DateTime(timezone=True))
    issue_stated_close = Column(DateTime(timezone=True))
    issue_actual_close = Column(DateTime(timezone=True))
    allottment_date = Column(DateTime(timezone=True))
    late_redemption = Column(DateTime(timezone=True))
    resale_start_date = Column(DateTime(timezone=True))
    transfer_agent = Column(String(255))
    transfer_agent_short_name = Column(String(255))
    transfer_agent_email = Column(String(255))
    amfi_code = Column(String(255))
    objective_text = Column(Text)
    benchmark = Column(String(255))
    rta_code = Column(String(255))
    colour = Column(Integer)
    isin_code = Column(String(255))
    modified_ts = Column(DateTime(timezone=True))
    is_dividend = Column(Boolean)
    auditor_code = Column(Integer)
    custodian_code = Column(Integer)
    is_direct_plan = Column(Boolean)
    reg_plan_id = Column(Integer)
    status = Column(String(255))
    new_fund = Column(Boolean)
    dividend_periodicity = Column(String(255))
    is_etf_fund = Column(Boolean)
    lock_in = Column(Boolean)
    lock_in_period_days = Column(Integer)
    variant = Column(Boolean)
    variant_fund_id = Column(Integer)
    is_rgess_plan = Column(Boolean)
    min_widw_unit = Column(Numeric)
    min_subsequent_investment_unit = Column(Numeric)
    min_investment_multiples = Column(Integer)
    transaction_status = Column(String(255))
    stated_annual_expense = Column(Numeric)
    max_inv_amount = Column(Integer)
    is_fof = Column(Boolean)
    last_etf_trade_date = Column(DateTime(timezone=True))
    is_index_fund = Column(Boolean)
    min_withdrawal_multiple_amount = Column(Integer)
    interest_risk_name = Column(String(255))
    credit_risk_name = Column(String(255))
    potential_risk_class = Column(String(255))
    fund_name = Column(String(255))
    minor_investments_allowed = Column(Boolean)
    created_at = Column(DateTime(timezone=True), nullable=False)
    updated_at = Column(DateTime(timezone=True), nullable=False)
    nav = Column(Integer, nullable=False)
